
spring:
  datasource:
    dynamic:
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      datasource:
        master:
          username: root
          password: 95093070557
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://localhost:3306/ruoyi

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
  thymeleaf:
    suffix: .html
    cache: false
    mode: LEGACYHTML5
server:
  port: 8087

mybatis-plus:
  mapper-locations: classpath:mapper/sys/*.xml
  check-config-location: false
  executor-type: simple
  type-aliases-package: com.zjt.sout.entity